/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controller;

/**
 *
 * @author Alejandro Rios
 */
public class AboutView extends View {
static  AboutView instance;
private void assignController(Controller c) {
      
        aboutButton.addActionListener(c);
        aboutButton.setActionCommand("START");
        
       
    }

 public static AboutView getInstance(Controller c) {
        if (instance == null) {
           instance=new AboutView(c);
        }
        return instance;
    }
    
    
    /**
     * Creates new form About
     */
    public AboutView(Controller c) {
         super(c);
        initComponents();
        assignController(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aboutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutButton.setBackground(new java.awt.Color(204, 204, 255));
        aboutButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        aboutButton.setText("INICIO");
        jPanel1.add(aboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("RJC es una aplicación creada en JAVA para \nrevisar si el código contenido en un archivo \ncumple con la estructura básica del lenguaje \nde programación JAVA. \nPara añadir el archivo, se debe copiar \nla ruta en una caja de texto que se \nproporciona. El archivo debe estar en \nformato .txt o .jar. No se garantiza que \nsi se enruta otro tipo de formato el \nprograma lo reconozca. Una vez se agrega \nla ruta y se prueba el código, \nse le muestra al usuario los errores \nen el código y por cada secuencia correcta,\n se genera una lista simplemente ligada \nque se muestra al usuario.  ");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 370, 320));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ACERCA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
