/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controller;

/**
 *
 * @author Alejandro Rios
 */
public class InitialView extends View {
static InitialView instance; 

    public InitialView(Controller c) {
        
        super(c);
        initComponents();
         asignarControlador(c);
        
    }
    /**
     * Creates new form vistaInicio
    
     */
   
        
       
    
    
    
private void asignarControlador(Controller c) {
        aboutButton.addActionListener(c);
        aboutButton.setActionCommand("ABOUT");
        closeButton.addActionListener(c);
        closeButton.setActionCommand("CLOSE");
        
        reviewCodeButton.addActionListener(c);
        reviewCodeButton.setActionCommand("REVIEW");
    }

 public static View getInstance(Controller c) {
        if (instance == null) {
           instance=new InitialView(c);
        }
        return instance;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aboutButton = new javax.swing.JButton();
        reviewCodeButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutButton.setBackground(new java.awt.Color(204, 204, 255));
        aboutButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        aboutButton.setText("Acerca de");
        jPanel1.add(aboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        reviewCodeButton.setBackground(new java.awt.Color(204, 204, 255));
        reviewCodeButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        reviewCodeButton.setText("Revisar código");
        jPanel1.add(reviewCodeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        closeButton.setBackground(new java.awt.Color(204, 204, 255));
        closeButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        closeButton.setText("Salir");
        jPanel1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setText("REVIEW JAVA CODE V0.1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reviewCodeButton;
    // End of variables declaration//GEN-END:variables
}
