/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controller;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Alejandro Rios
 */
public class ReviewCodeView extends View {

    static ReviewCodeView instance; 
    
    public ReviewCodeView(Controller c) {
        super(c);
        initComponents();
        assignController(c);
    }

    /**
     * Creates new form vistaRevisar
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pathText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        responseText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        testCodeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pathText.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        pathText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextActionPerformed(evt);
            }
        });
        jPanel1.add(pathText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 350, 30));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel1.setText("RUTA DE CÓDIGO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        responseText.setColumns(20);
        responseText.setRows(5);
        jScrollPane1.setViewportView(responseText);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 1020, 290));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("INGRESE RUTA DEL ARCHIVO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 300, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Resultado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        newButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        newButton.setText("Evaluar nuevo código");
        jPanel1.add(newButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 230, 30));

        startButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        startButton.setText("Inicio");
        jPanel1.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 70, 30));

        testCodeButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        testCodeButton.setText("Probar");
        testCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testCodeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(testCodeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testCodeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testCodeButtonActionPerformed

    private void pathTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTextActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField pathText;
    private javax.swing.JTextArea responseText;
    private javax.swing.JButton startButton;
    private javax.swing.JButton testCodeButton;
    // End of variables declaration//GEN-END:variables

     public static View getInstance(Controller c) {
        if (instance == null) {
           instance=new ReviewCodeView(c);
        }
        return instance;
    }

    public JTextField getPathText() {
        return pathText;
    }

    public void setPathText(JTextField pathText) {
        this.pathText = pathText;
    }

    public JTextArea getResponseText() {
        return responseText;
    }

    public void setResponseText(JTextArea responseText) {
        this.responseText = responseText;
    }

    public JButton getTestCodeButton() {
        return testCodeButton;
    }

  
    
    private void assignController(Controller c) {
        newButton.addActionListener(c);
        newButton.setActionCommand("NEW");

        testCodeButton.addActionListener(c);
        testCodeButton.setActionCommand("TEST");

        //selectButton.addActionListener(c);
       // selectButton.setActionCommand("SELECT");

        startButton.addActionListener(c);
        startButton.setActionCommand("START");
    }

}
